export const GAME_GENRES = [
  'Action',
  'Adventure',
  'Role-Playing (RPG)',
  'Simulation',
  'Strategy',
  'Sports',
  'Puzzle',
  'Shooter',
  'Fighting',
  'Racing',
  'Platformer',
  'Horror',
  'Music',
  'Sandbox',
  'Survival',
  'Stealth',
  'MMORPG',
  'Party',
  'Visual Novel',
  'Metroidvania',
  'Roguelike',
  'Battle Royale',
  'Hack and Slash',
  'Rhythm'
]

export const GAME_CATEGORIES = [
  'Main Game',
  'DLC/Addon',
  'Expansion',
  'Bundle',
  'Standalone Expansion',
  'Mod',
  'Episode',
  'Season',
  'Remake',
  'Remaster',
  'Expanded Game',
  'Port',
  'Fork',
  'Pack',
  'Update'
]

export const GAME_MODES = [
  'Single-player',
  'Multiplayer',
  'Co-op',
  'Split-screen',
  'Online Multiplayer',
  'Local Multiplayer',
  'PvP (Player vs Player)',
  'PvE (Player vs Environment)',
  'Battle Royale',
  'Campaign',
  'Sandbox',
  'Survival',
  'Creative',
  'Time Attack',
  'Free Roam',
  'Turn-based',
  'Real-time Strategy',
  'Team-based',
  'Deathmatch',
  'Capture the Flag'
]

export const LANGUAGES = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Japanese',
  'Chinese',
  'Korean',
  'Russian',
  'Dutch',
  'Polish',
  'Swedish',
  'Arabic',
  'Turkish',
  'Greek',
  'Hindi',
  'Thai',
  'Vietnamese',
  'Norwegian',
  'Danish',
  'Finnish',
  'Hungarian',
  'Czech'
]

export const CHARACTER_GENDERS = ['Male', 'Female', 'Unknown']

export const CHARACTER_SPECIES = [
  'Human',
  'Alien',
  'Orc',
  'Vampire',
  'Demon',
  'Angel',
  'Dragon',
  'Ghost',
  'Fairy',
  'Troll',
  'Reptilian',
  'Insectoid',
  'Plant-based',
  'Anthropomorphic Animal',
  'Mystical Creature',
  'Unknown'
]

export const COUNTRIES = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia and Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina Faso',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Republic',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo (Brazzaville)',
  'Congo (Kinshasa)',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Eswatini',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'North Korea',
  'North Macedonia',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russia',
  'Rwanda',
  'Saint Kitts and Nevis',
  'Saint Lucia',
  'Saint Vincent and the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome and Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Korea',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Timor-Leste',
  'Togo',
  'Tonga',
  'Trinidad and Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
]
